rails_app/config/routes.rb
RailsApp::Application.routes.draw do

  resources :games
  resources :players
  devise_for :admins
  root :to => "games#index"

end

rails_app/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

rails_app/app/models/game.rb
class Game < ActiveRecord::Base
   validates_presence_of :title, :description
   validates_attachment_presence :image
   
   has_many :game_players
   has_many :players, :through => :game_players

   has_attached_file :image,
                     :path => ":rails_root/public/images/:id/:style/:basename.:extension",
                     :url  => "/images/:id/:style/:basename.:extension"

end

rails_app/app/models/game_player.rb
class GamePlayer < ActiveRecord::Base
    belongs_to :game
    belongs_to :player
end

rails_app/app/models/player.rb
class Player < ActiveRecord::Base
  validates_presence_of :name
  
  has_many :games
  has_many :games, :through => :game_players
end

rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails_app/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game ||= Game.new
  end

  def create
    @game = Game.new(params[:game])
    if @game.save
      redirect_to(@game, :notice => 'Game was successfully created.')  
    else
      render :action => :new
    end
  end

end

rails_app/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :authenticate_admin!
  
  def index
    @players = Player.all
  end

  def edit
    @player ||= Player.find(params[:id])
  end

  def new
    @player ||= Player.new
    render :action => :edit
  end

  def update
    @player ||= Player.find(params[:id])
    @player.update_attributes(params[:player])
    if @player.save
      redirect_to(players_path, :notice => 'Player was successfully updated.')  
    else
      render :action => :edit
    end
  end

  def create
    @player = Player.new
    update
  end
  
  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to(players_path, :notice => 'Player was deleted.')
  end
end

rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_app/app/helpers/games_helper.rb
module GamesHelper
end

rails_app/app/helpers/players_helper.rb
module PlayersHelper
end

rails_app/app/views/games/index.html.haml
%h1 Listing games

- @games.each do |game|
  %br
  =link_to game.title, game
%p
  = link_to 'New Game', "/games/new"

rails_app/app/views/games/new.html.haml
%h1 New game

= form_for @game, :html => { :multipart => true } do |f|
  - if @game.errors.any?
    #error_explanation
      %h2 #{pluralize(@game.errors.count, "error")} prohibited this game from being saved:
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br
    = f.text_field :title
  .field
    = f.label :description
    %br
    = f.text_area :description

  .field
    = f.label :image
    %br
    = f.file_field :image
  .actions
    = f.submit

= link_to 'Back', games_path

rails_app/app/views/games/show.html.haml
%p
  %b Title:
  = @game.title

%p
  %b Description:
  = @game.description

= image_tag @game.image.url

%h3 Players in this game

- @game.players.each do |player|
  %p= player.name

%br
= link_to 'Back', games_path

rails_app/app/views/layouts/application.html.haml
!!! Strict
%html
  %head
    %title="Rails App #{yield :page_title}"
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    %p.notice
      = notice
    %p.alert
      = alert
    = yield

rails_app/app/views/players/edit.html.haml
%h1 New/Edit Player

= form_for @player, :html => { :multipart => true } do |f|
  - if @player.errors.any?
    #error_explanation
      %h2 #{pluralize(@player.errors.count, "error")} prohibited this player from being saved:
      %ul
        - @player.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br
    = f.text_field :name
  .actions
    = f.submit

= link_to 'Player List', players_path

rails_app/app/views/players/index.html.haml
%h1 Listing players

- @players.each do |player|
  %br
  =link_to player.name, edit_player_path(player)
  =link_to "delete", player, :confirm=> "Are you sure", :method => :delete
%p
  = link_to 'New Player', "/players/new"